#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pathos
Version  : 0.2.9
Release  : 6
URL      : https://github.com/uqfoundation/pathos/releases/download/pathos-0.2.9/pathos-0.2.9.tar.gz
Source0  : https://github.com/uqfoundation/pathos/releases/download/pathos-0.2.9/pathos-0.2.9.tar.gz
Summary  : parallel graph management and execution in heterogeneous computing
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pathos-bin = %{version}-%{release}
Requires: pathos-license = %{version}-%{release}
Requires: pathos-python = %{version}-%{release}
Requires: pathos-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(dill)
BuildRequires : pypi(multiprocess)
BuildRequires : pypi(pox)
BuildRequires : pypi(ppft)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
Notes:
-----
Contains two "extended" examples:
1) scatter-gather, with different parallel backends
2) optimization, with different parallel backends

%package bin
Summary: bin components for the pathos package.
Group: Binaries
Requires: pathos-license = %{version}-%{release}

%description bin
bin components for the pathos package.


%package license
Summary: license components for the pathos package.
Group: Default

%description license
license components for the pathos package.


%package python
Summary: python components for the pathos package.
Group: Default
Requires: pathos-python3 = %{version}-%{release}

%description python
python components for the pathos package.


%package python3
Summary: python3 components for the pathos package.
Group: Default
Requires: python3-core
Provides: pypi(pathos)
Requires: pypi(dill)
Requires: pypi(multiprocess)
Requires: pypi(pox)
Requires: pypi(ppft)

%description python3
python3 components for the pathos package.


%prep
%setup -q -n pathos-0.2.9
cd %{_builddir}/pathos-0.2.9
pushd ..
cp -a pathos-0.2.9 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656428198
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pathos
cp %{_builddir}/pathos-0.2.9/LICENSE %{buildroot}/usr/share/package-licenses/pathos/89215dbe96039235796b31ac8e2aa8f659d5c12b
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pathos_connect
/usr/bin/portpicker

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pathos/89215dbe96039235796b31ac8e2aa8f659d5c12b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
