#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pathos
Version  : 0.2.8
Release  : 3
URL      : https://github.com/uqfoundation/pathos/releases/download/pathos-0.2.8/pathos-0.2.8.tar.gz
Source0  : https://github.com/uqfoundation/pathos/releases/download/pathos-0.2.8/pathos-0.2.8.tar.gz
Summary  : parallel graph management and execution in heterogeneous computing
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pathos-bin = %{version}-%{release}
Requires: pathos-license = %{version}-%{release}
Requires: pathos-python = %{version}-%{release}
Requires: pathos-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(dill)
BuildRequires : pypi(multiprocess)
BuildRequires : pypi(pox)
BuildRequires : pypi(ppft)
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
--------------------------------------------------------------------------
pathos: parallel graph management and execution in heterogeneous computing
--------------------------------------------------------------------------

%package bin
Summary: bin components for the pathos package.
Group: Binaries
Requires: pathos-license = %{version}-%{release}

%description bin
bin components for the pathos package.


%package license
Summary: license components for the pathos package.
Group: Default

%description license
license components for the pathos package.


%package python
Summary: python components for the pathos package.
Group: Default
Requires: pathos-python3 = %{version}-%{release}

%description python
python components for the pathos package.


%package python3
Summary: python3 components for the pathos package.
Group: Default
Requires: python3-core
Provides: pypi(pathos)
Requires: pypi(dill)
Requires: pypi(multiprocess)
Requires: pypi(pox)
Requires: pypi(ppft)

%description python3
python3 components for the pathos package.


%prep
%setup -q -n pathos-0.2.8
cd %{_builddir}/pathos-0.2.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644189321
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pathos
cp %{_builddir}/pathos-0.2.8/LICENSE %{buildroot}/usr/share/package-licenses/pathos/5a4d5da357f0df5d1be0dd74d0e4cc9830053a7c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pathos_connect
/usr/bin/portpicker

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pathos/5a4d5da357f0df5d1be0dd74d0e4cc9830053a7c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
